# Generated by Django 4.2.16 on 2026-03-18 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
                ('import_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='uploads.importrow')),
            ],
            options={
                'verbose_name': 'Review Action',
                'verbose_name_plural': 'Review Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
