# Generated by Django 4.2.16 on 2026-03-18 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMasterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal snake_case key (e.g., item_name)', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Boolean')], default='string', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display ordering')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standard Master Field',
                'verbose_name_plural': 'Standard Master Fields',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('assigned', 'Assigned to Distributor')], default='global', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(blank=True, help_text='Leave blank for global templates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='distributors.distributor')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='field_templates.template')),
            ],
            options={
                'verbose_name': 'Template Version',
                'verbose_name_plural': 'Template Versions',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='FieldAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_normalized', models.CharField(help_text='Auto-normalized alias (set automatically on save)', max_length=200)),
                ('alias_original', models.CharField(help_text='Original alias as entered by user', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='field_templates.standardmasterfield')),
            ],
            options={
                'verbose_name': 'Field Alias',
                'verbose_name_plural': 'Field Aliases',
                'ordering': ['standard_field__name', 'alias_original'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(help_text='Original column header name as seen in distributor files', max_length=200)),
                ('source_column_normalized', models.CharField(help_text='Auto-normalized version of source_column', max_length=200)),
                ('standard_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_mappings', to='field_templates.standardmasterfield')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='field_templates.templateversion')),
            ],
            options={
                'verbose_name': 'Template Field Mapping',
                'verbose_name_plural': 'Template Field Mappings',
                'ordering': ['standard_field__order'],
                'unique_together': {('template_version', 'standard_field')},
            },
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('distributor__isnull', True), ('scope', 'global')), models.Q(('distributor__isnull', False), ('scope', 'assigned')), _connector='OR'), name='template_scope_distributor_consistency'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldalias',
            unique_together={('standard_field', 'alias_normalized')},
        ),
    ]
