# Generated by Django 4.2.16 on 2026-03-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardmasterfield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this field in reports, exports, and Master Data'),
        ),
    ]
