# Generated by Django 4.2.16 on 2026-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_templates', '0002_add_is_active_to_standard_master_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardmasterfield',
            name='batch_context_source',
            field=models.CharField(blank=True, choices=[('', 'No auto-fill (read from file)'), ('distributor.name', 'Distributor Name (from login)'), ('distributor.code', 'Distributor Code (from login)'), ('distributor.area.name', 'Area Name (from distributor)')], default='', help_text='Auto-fill this field from batch metadata instead of reading from the uploaded file', max_length=50),
        ),
    ]
