# Generated by Django 4.2.16 on 2026-04-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_area_alter_distributor_area'),
        ('field_templates', '0003_add_batch_context_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='template',
            name='template_scope_distributor_consistency',
        ),
        migrations.AlterField(
            model_name='template',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Distributor this template belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='distributors.distributor'),
        ),
        migrations.AlterField(
            model_name='template',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('assigned', 'Assigned to Distributor')], default='assigned', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('scope', 'global'), ('distributor__isnull', True)),
                    models.Q(('scope', 'assigned'), ('distributor__isnull', False)),
                    _connector='OR',
                ),
                name='template_scope_distributor_consistency',
            ),
        ),
    ]
