# Generated by Django 4.2.16 on 2026-04-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_area_alter_distributor_area'),
        ('field_templates', '0004_remove_global_scope_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='template',
            name='template_scope_distributor_consistency',
        ),
        migrations.AlterField(
            model_name='template',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global templates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='distributors.distributor'),
        ),
        migrations.AlterField(
            model_name='template',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('assigned', 'Assigned to Distributor')], default='global', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('distributor__isnull', True), ('scope', 'global')), models.Q(('distributor__isnull', False), ('scope', 'assigned')), _connector='OR'), name='template_scope_distributor_consistency'),
        ),
    ]
