# Generated by Django 4.2.16 on 2026-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_templates', '0005_remove_template_template_scope_distributor_consistency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardmasterfield',
            name='is_required',
        ),
        migrations.AddField(
            model_name='standardmasterfield',
            name='is_displayed',
            field=models.BooleanField(default=True, help_text='Show this field as a column in Master Data, exports, and reports'),
        ),
        migrations.AlterField(
            model_name='standardmasterfield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Process this field (aliases, mapping, validation). Hidden fields are still processed if active.'),
        ),
    ]
