# Generated by Django 4.2.16 on 2026-04-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_templates', '0006_replace_required_with_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label text to search for in PDF header (e.g. "Invoice Id", "Customer", "Telp")', max_length=200)),
                ('standard_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='header_mappings', to='field_templates.standardmasterfield')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_mappings', to='field_templates.templateversion')),
            ],
            options={
                'verbose_name': 'Header Field Mapping',
                'verbose_name_plural': 'Header Field Mappings',
                'ordering': ['standard_field__order'],
                'unique_together': {('template_version', 'standard_field')},
            },
        ),
    ]
