# Generated by Django 4.2.16 on 2026-04-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_templates', '0007_add_header_field_mapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatefieldmapping',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='FieldAlias',
        ),
    ]
