# Generated by Django 4.2.16 on 2026-04-12 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('reprocess', 'Reprocess'), ('approve', 'Approve'), ('reject', 'Reject'), ('finalize', 'Finalize'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('other', 'Other')], db_index=True, max_length=20)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text="Model name or resource type (e.g. 'UploadBatch', 'Product')", max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='ID of the target, stringified', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (changed fields, values, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx'), models.Index(fields=['action', '-created_at'], name='core_activi_action_a01617_idx')],
            },
        ),
    ]
