# Generated by Django 4.2.16 on 2026-03-18 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_templates', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprocessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocess_logs', to='uploads.uploadbatch')),
                ('new_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocess_new', to='uploads.processingrun')),
                ('old_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocess_old', to='uploads.processingrun')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocess_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reprocess Log',
                'verbose_name_plural': 'Reprocess Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, help_text='Denormalized from distributor.area', max_length=100)),
                ('data', models.JSONField(help_text='Standardized field data {field_name: value}')),
                ('business_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_records', to='distributors.distributor')),
                ('import_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_record', to='uploads.importrow')),
                ('processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_records', to='uploads.processingrun')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_records', to='field_templates.templateversion')),
            ],
            options={
                'verbose_name': 'Master Data Record',
                'verbose_name_plural': 'Master Data Records',
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['area', 'distributor'], name='master_data_area_ac9989_idx'), models.Index(fields=['imported_at'], name='master_data_importe_0fe100_idx')],
            },
        ),
    ]
