# Generated by Django 4.2.16 on 2026-04-02 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributors', '0002_area_alter_distributor_area'),
        ('uploads', '0002_templatematchlog_matched_columns_unmatched_columns'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Auto-generated IID-XXXXX', max_length=20, unique=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_imports', to='distributors.distributor')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.processingrun')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='masterdatarecord',
            name='master_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='master_data.masterdataimport'),
        ),
    ]
