# Generated by Django 4.2.16 on 2026-04-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0002_area_alter_distributor_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_sku', models.CharField(blank=True, help_text="Distributor's own SKU for this product", max_length=50)),
                ('alias_name', models.CharField(blank=True, help_text="Distributor's own product name", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='distributors.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(help_text='e.g. PCS, BOX, KG', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_identifier_field', models.CharField(help_text="StandardMasterField.name used as product identifier (e.g. 'item_name')", max_length=100)),
                ('quantity_field', models.CharField(help_text="StandardMasterField.name holding the quantity (e.g. 'quantity')", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse Field Configuration',
            },
        ),
        migrations.CreateModel(
            name='MainStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_stock', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock. Can be negative.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='warehouse.distributorproduct')),
            ],
        ),
        migrations.AddField(
            model_name='distributorproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_products', to='warehouse.product'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Amount moved (always positive)')),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. ProcessingRun #5 or Batch #12', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('distributor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.distributorproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['distributor_product', '-created_at'], name='warehouse_s_distrib_9b977a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='distributorproduct',
            index=models.Index(fields=['distributor', 'alias_sku'], name='warehouse_d_distrib_956857_idx'),
        ),
        migrations.AddIndex(
            model_name='distributorproduct',
            index=models.Index(fields=['distributor', 'alias_name'], name='warehouse_d_distrib_db5130_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distributorproduct',
            unique_together={('distributor', 'product')},
        ),
    ]
