# Generated by Django 4.2.16 on 2026-04-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousefieldconfig',
            name='min_stock_threshold',
            field=models.IntegerField(default=10, help_text='Show notification when distributor stock falls to or below this value'),
        ),
    ]
