# Generated by Django 4.2.16 on 2026-04-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousefieldconfig_min_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousefieldconfig',
            name='quantity_field',
            field=models.CharField(blank=True, default='', help_text='StandardMasterField.name holding the quantity. Leave empty to use 1 per row.', max_length=100),
        ),
    ]
