# Generated by Django 4.2.16 on 2026-03-18 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(help_text='Original data as read from file')),
                ('mapped_data', models.JSONField(default=dict, help_text='Data mapped to standard field names')),
                ('row_checksum', models.CharField(db_index=True, max_length=64)),
                ('row_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('warning', 'Warning'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='pending_review', max_length=20)),
                ('review_decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import Row',
                'verbose_name_plural': 'Import Rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('used_global', models.BooleanField(default=False)),
                ('fallback_happened', models.BooleanField(default=False)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Processing Run',
                'verbose_name_plural': 'Processing Runs',
                'ordering': ['-run_number'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('file', 'File'), ('template', 'Template'), ('row', 'Row'), ('business', 'Business'), ('review', 'Review')], max_length=20)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('code', models.CharField(help_text='e.g. REQUIRED_FIELD_MISSING', max_length=50)),
                ('message', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='uploads.importrow')),
            ],
            options={
                'verbose_name': 'Validation Issue',
                'verbose_name_plural': 'Validation Issues',
                'ordering': ['severity', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Path relative to MEDIA_ROOT', max_length=500)),
                ('file_checksum', models.CharField(help_text='SHA-256 of the uploaded file', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error'), ('mismatch', 'Template Mismatch')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='distributors.distributor')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('matched', models.BooleanField()),
                ('is_assigned', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('processing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='uploads.processingrun')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='field_templates.templateversion')),
            ],
            options={
                'verbose_name': 'Template Match Log',
                'ordering': ['-match_score'],
            },
        ),
        migrations.AddField(
            model_name='processingrun',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='uploads.uploadbatch'),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs', to='field_templates.templateversion'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='processing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_rows', to='uploads.processingrun'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rows', to=settings.AUTH_USER_MODEL),
        ),
    ]
