# Generated by Django 4.2.16 on 2026-04-12 15:30

from django.db import migrations, models


def backfill_review_codes(apps, schema_editor):
    UploadBatch = apps.get_model("uploads", "UploadBatch")
    for batch in UploadBatch.objects.filter(review_code="").order_by("pk"):
        batch.review_code = f"RID-{batch.pk:05d}"
        batch.save(update_fields=["review_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_templatematchlog_matched_columns_unmatched_columns'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='uploadbatch',
            name='review_code',
            field=models.CharField(blank=True, default='', help_text='Auto-generated Review ID (RID-XXXXX)', max_length=20),
        ),
        # Step 2: Backfill existing rows
        migrations.RunPython(backfill_review_codes, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='uploadbatch',
            name='review_code',
            field=models.CharField(blank=True, help_text='Auto-generated Review ID (RID-XXXXX)', max_length=20, unique=True),
        ),
    ]
