# Generated by Django 4.2.16 on 2026-03-18 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(help_text='Geographic or business area (e.g., WEST, EAST)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDistributorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributors.distributor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-Distributor Assignment',
                'verbose_name_plural': 'User-Distributor Assignments',
                'ordering': ['distributor__name', 'user__username'],
                'unique_together': {('user', 'distributor')},
            },
        ),
    ]
