# Generated by Django 4.2.16 on 2026-03-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. WEST JAVA, EAST, SUMATRA', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. WJAV, EAST', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='distributor',
            name='area',
            field=models.ForeignKey(help_text='Geographic or business area', on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='distributors.area'),
        ),
    ]
